### ISSUE TITLE
Image range processing in the experiment stage

### ISSUE THREAD

**Issue by Yliu724** [dmarnerides/hdr-expandnet#10]
Hi, @dmarnerides 

Your work is really impressive! 
Here I have a problem when comparing the results with other methods. Supposing the range of the ground truth is [0, 1000], then different methods may get a different range of the predicted image, either from [0, 1] or [0, n]. From Issue #9, I can see that there are two methods to scale the range of the image in your network,  I would like to know whether you scale the range of images predicted by other methods before computing the score of PSNR, SSIM, etc? If so, how did you do it? Thanks a lot!

**Comment by dmarnerides** [comment]
Hi there,

Thank you for your interest. The images are scaled in the same way for all methods, including ExpandNet, as mentioned in the paper. 

1. If the scaling is built-in for a particular method (i.e. max luminance is needed for the EO): 
  > For the display-referred scaling, the maximum luminance of the display is given as a parameter to     the EO algorithm.
  > For the scene-referred (original HDR range) scaling, the default value of the algorithm is used and then scaled linearly to match the original HDR. 
2. If the scaling is not built in, then the scaling is done in the same way as for ExpandNet.

The rest is the same as described in the paper (e.g. scale the 0.1 and 99.9 percentiles to match the corresponding percentiles in the target range).

Hope this helps,
Demetris
