### ISSUE TITLE
Where can I get the dataset?

### ISSUE THREAD

**Issue by lordbutters** [dmarnerides/hdr-expandnet#11]
I wanna to train a model by myself, but I couldn't find the dataset used in your paper. Could you provide the dataset that uesd in your paper?

**Comment by dmarnerides** [comment]
Hello there,

Thank you for the interest. Unfortunately, I can't share the dataset at the moment. 

However, over the years, some (probably) better datasets have appeared like this one:
https://hdrplusdata.org/

Or this one:
https://www.cmlab.csie.ntu.edu.tw/~yulunliu/SingleHDR/

Perhaps you can consider using one of these.

Also the Fairchild HDR Photographic Survey dataset (which is also calibrated - and was used for ExpandNet) is still online and available for use:
http://rit-mcsl.org/fairchild//HDR.html

Hope this helps,
Best,
Demetris
