### ISSUE TITLE
Inquiry about Dataset

### ISSUE THREAD

**Issue by SooonChang** [dmarnerides/hdr-expandnet#12]
Where can I get the dataset which is needed for training.

**Comment by dmarnerides** [comment]
Most of the dataset is in the sources mentioned here: #5 #11
Some are also found here: https://www.scss.tcd.ie/Emin.Zerman/databaseInformations/_hdrImgVidList.html
Only a few are in-house images that unfortunately I can't share. It shouldn't make much difference in the training.

**Comment by SooonChang** [comment]
I apologize that I didn't check closed issues. I didn't recognize it. And thanks for replying.

**Comment by SooonChang** [comment]
> Most of the dataset is in the sources mentioned here: #5 #11
> Some are also found here: https://www.scss.tcd.ie/Emin.Zerman/databaseInformations/_hdrImgVidList.html
> Only a few are in-house images that unfortunately I can't share. It shouldn't make much difference in the training.

I apologize that I didn't check closed issues. I didn't recognize it. And thanks for replying.

**Comment by dmarnerides** [comment]
No worries. Hope it helps!
