### ISSUE TITLE
Question about video dataset

### ISSUE THREAD

**Issue by 114569** [dmarnerides/hdr-expandnet#13]
Thank you for your work. 
I have a question about LDR video dataset.

Can you share dataset which you used for video test?

**Comment by dmarnerides** [comment]
Hello,

I used this Video:
https://commons.wikimedia.org/wiki/File:Brzansko-Moraviste-Pejzazi_20170226_4457.webm

It's under the creative commons license (Attribution-ShareAlike 4.0 International (CC BY-SA 4.0))

Best,
Demetris
