### ISSUE TITLE
durand tmo is not avalable

### ISSUE THREAD

**Issue by 8bignic8** [dmarnerides/hdr-expandnet#15]
If I want to use [durand](https://github.com/dmarnerides/hdr-expandnet/blob/2b47572a88f247e0f44eb14065b0ed4fc9618e0d/util.py#L181) tmo it errors out.

**Comment by dmarnerides** [comment]
That would be the case if your python opencv is not compiled with the
durand tmo included as is the case with the opencv-python version. The
solution would be to either install a version of opencv that has it /
compile opencv from scratch, or disable the durand tmo when training.

**Comment by dmarnerides** [comment]
Btw, it is not included in some builds of OpenCV because it is proprietary (see [this issue](https://github.com/opencv/opencv/issues/14468))

**Comment by 8bignic8** [comment]
Its sad that it is proprietary. I just disabled it out. Thanks :)
