### ISSUE TITLE
Which version of PyTorch do you use in this project?

### ISSUE THREAD

**Issue by jundanl** [dmarnerides/hdr-expandnet#17]
Hi,

Thank you for sharing this great work!

I wonder which version of PyTorch do you use in this project?

**Comment by dmarnerides** [comment]
Hi there,

Thank you for the interest!

The original was developed in version 0.2 but this repo was updated to work with post 0.3, maybe even 0.4 (major change was the removal of Variable). I think it should be fine with the current version (1.8) too though.
