### ISSUE TITLE
about hdr image save

### ISSUE THREAD

**Issue by sunyclj** [dmarnerides/hdr-expandnet#19]
In the pre-processing stage, the range of HDR is set at [0,1] by np.interp() after reading HDR, and the same is true when saving HDR image. Won't the information of HDR image be lost in this way?

**Comment by t2ac32** [comment]
Not really since .interp()_ will do as many decimals as required to intepret de previous scale. 
The idea of having [0,1] is to have more decimals to interpret your pixels colors.

When reading your HDR it will be of importance which colorspace are you using to show the images, Since a colorspace with "few" tones will do a bad job interpreting step changes.

**Comment by dmarnerides** [comment]
Sorry I thought I had answered this but my email response did not get here for some reason. Here it is:

"Not really, as the predictions are of relative luminance, so a linear scaling won't lose information (unless we are comparing across images, e.g. video frames -- which is something that should be considered in the experimental video implementation here). 

The output can be rescaled linearly without loss, to match a display or absolute units if we have values for those.

(this of course assumes enough floating point precision which we almost surely have here when using float)"

**Comment by dmarnerides** [comment]
Not really, as the predictions are of relative luminance, so a linear
scaling won't lose information (unless we are comparing across images, e.g.
video frames -- which is something that should be considered in the
experimental video implementation here).

The output can be rescaled linarly without loss, to match a display or
absolute units if we have values for those.

(this of course assumes enough floating point presicion which we almost
surely have here when using float)
