### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by ghost** [dmarnerides/hdr-expandnet#20]
It gives same LDR output

**Comment by dmarnerides** [comment]
What do you mean?

**Comment by ghost** [comment]
When I give a .jpg input, it gives a .hdr output. But it does not have a High Dynamic Range, it is the same as the jpg just in hdr format. Can you please help me to get it working? I would be much obliged.

**Comment by dmarnerides** [comment]
I think if you get the HDR it means it's working. Not sure what exactly the problem is. The .hdr is linearised, without gamma, without CRF and needs
tone mapping to get back to the LDR.

There won't be expansion (hallucination) in the under/overexposed areas as
that was not in the scope of the project.

For more information have a look at the paper linked in the README page.

**Comment by ghost** [comment]
https://we.tl/t-mmz0jJfFBr

have a look here. it has a input file and the output i get from your code.

**Comment by ghost** [comment]
In the git description, as you mentioned it takes a ldr input and gives a hdr output

![image](https://github.com/dmarnerides/hdr-expandnet/assets/33053458/e58ac563-6bd7-4b24-85f7-68a631d937e5)

I am just trying to do that, could you please help me in this...... please...

**Comment by dmarnerides** [comment]
I'm sorry, I can't help you more than what I already have described.

I would suggest that you read up on HDR literature and come back to this.

**Comment by ghost** [comment]
Can you explain what exactly is your code doing instead of just changing the extension from jpg to hdr?

**Comment by dmarnerides** [comment]
If you simply change a .jpg to .hdr it won't be like this. All the information about what the code is doing is here:

https://arxiv.org/abs/1803.02266

I'm closing the issue as this isn't an actual issue.

**Comment by avidews** [comment]
Hhahahahahahhahahahahaahahahah, thanks

**Comment by avidews** [comment]
Please remove this git from github.

**Comment by avidews** [comment]
It's waste

**Comment by avidews** [comment]
It's absolutely waste of time and efforts that I have to put here. Why don't you simply remove this git from the github repository Its wasting time of people who are trying to run this code, and they get nothing out of it absolutely nothing. Let me just send you a simple gpg to hdr conversion and see what is the difference that your code is making as compared to that conversion.

**Comment by dmarnerides** [comment]
I would suggest that you try and calm yourself down and consider that there are some things that you don't know about that you can learn.

A good book to start with is:
https://books.google.com.cy/books/about/Advanced_High_Dynamic_Range_Imaging.html?id=6JguDwAAQBAJ&source=kp_book_description&redir_esc=y

The paper in this repo is another good source
