### ISSUE TITLE
why it is not giving a hdr output?

### ISSUE THREAD

**Issue by krisnegi123** [dmarnerides/hdr-expandnet#21]
I ran this code, but i dont get any luminance in my hdr output.

**Comment by dmarnerides** [comment]
Do you mean the luminance channel is fully black? are the chrominance
channels there?

One thing that might be going wrong here is that the output is scaled to
[0, 1] and your viewer might be quantizing it all to 0?

Is this related to #20?

**Comment by krisnegi123** [comment]
No I dont think it related to #20 

I am viewing in photoshop

**Comment by krisnegi123** [comment]
What I want to do is, input a 360 LDR image and get a HDR output that I can use as HDRi map in 3D applications for lighting.

**Comment by dmarnerides** [comment]
Ok sounds good. The luminance output here is in relative units and scaled
to [0,1] so you'll need to rescale the image (just multiply) to the max
luminance of your scene to get the absolute luminance values for your
render.

If you also know the black level, you can add that too.


So if x is the hdr output you need to do something like:
y = (x - min_x) / (max_x - min_x)
result = y*max_luminance + black_level

or straight:
result = x*max_luminance + black_level

(assuming black level << max_luminance)

**Comment by krisnegi123** [comment]
Thanks a lot for your reply, I really appreciate that.

Can you please guide me how to implement this in your code?

**Comment by krisnegi123** [comment]
I am basically building something like this https://polyhaven.com/a/rural_asphalt_road

**Comment by krisnegi123** [comment]
And do I have to train first before using? Or it has pretrained data?

**Comment by krisnegi123** [comment]
Can you please help me?

**Comment by krisnegi123** [comment]
??????????????????????????????????????

**Comment by dmarnerides** [comment]
You will need to get the output of the model in the script and then apply the transformation i explained above and use that instead.

I am sorry but I don't have time to implement anything specific for your needs.

Also, patience is not the ability to wait, but the ability to keep a good attitude while waiting.

**Comment by krisnegi123** [comment]
Do you know how much trouble one has to go through without any answers.

**Comment by krisnegi123** [comment]
It's better to write clearly that this code is not for creating HDR.

**Comment by dmarnerides** [comment]
The literature would disagree. There have been many papers that use this same code and replicate the results, generating HDR images absolutely fine.

Maybe you're expecting absolute luminance values, while the model is outputting relative values. Maybe your idea of what HDR means is different or wrong. I don't know and I'm really sorry, but I can't help you any more with this as it is beyond the scope of this repository and this work.
