### ISSUE TITLE
Any updates on Training Source? 

### ISSUE THREAD

**Issue by cmooreml** [dmarnerides/hdr-expandnet#3]
This would help jump start testing the network for our research. Thanks very much.

https://github.com/dmarnerides/hdr-expandnet/issues/1

Author is working on his PhD and has not had time to clean up the training code. This project may be a good reference for people looking to train: https://github.com/echolijinghui/ExpandNet

**Comment by dmarnerides** [comment]
Hi, thanks for the patience. I will implement a minimal version of the training code with the current version of PyTorch within the next two weeks. Reopening this for reference.

**Comment by t2ac32** [comment]
Commenting to come  back and check for Pytorch code.

**Comment by dmarnerides** [comment]
Update: Working on it, I will need a bit more time.

**Comment by dmarnerides** [comment]
Update: Added training code.
