### ISSUE TITLE
First line almost black

### ISSUE THREAD

**Issue by martinmCGG** [dmarnerides/hdr-expandnet#4]
Hello,

I have noticed the prediction images contain darkened first line (and also the left and right borders).
It might be caused by zero-padding in the Conv2D layer, but I have not investigated the issue in-depth.

Example input image:
![gcanyon_c_yumapoint_3k exr](https://user-images.githubusercontent.com/46198010/52522529-e0301c80-2c86-11e9-9d7f-e1682b5629a6.jpg)

Original pixel values (a screenshot of the tev image viewer):
<img width="1136" alt="screen shot 2019-02-09 at 16 23 10" src="https://user-images.githubusercontent.com/46198010/52522637-436e7e80-2c88-11e9-987a-214efc61da49.png">

Prediction result with the artifact:
<img width="1136" alt="screen shot 2019-02-09 at 16 23 13" src="https://user-images.githubusercontent.com/46198010/52522618-f9859880-2c87-11e9-848e-51f6ae2e7cc8.png">

Please let me know in case you need more information.

**Comment by dmarnerides** [comment]
Hi, sorry for the late response. I replicated the issue and found the culprit. It was the replace_specials_ function which was attempting to remove infs and NaNs from the input. It wasn't properly working so I just removed it since it doesn't add much value, and it fixes the problem.
