### ISSUE TITLE
How to get the in-house HDR image?

### ISSUE THREAD

**Issue by ChuangbinC** [dmarnerides/hdr-expandnet#5]
Hi, I want to know how do you get the in-house HDR images? If you use a camera to take those picture and how do you make sure those images are HDR images? Thank~~

**Comment by dmarnerides** [comment]
Hi, the in-house HDR images are from multiple sources (e.g. the [Fairchild Photographic Survey](http://rit-mcsl.org/fairchild//HDR.html)) and still frames from videos. Using cameras, the HDR images are usually formed using bracketed exposures. You can compute the dynamic range of the HDR image to check how "HDR" it is.
