### ISSUE TITLE
Can expanded output be in .exr format instead of .hdr format? or need more details on .hdr

### ISSUE THREAD

**Issue by ittim4** [dmarnerides/hdr-expandnet#6]
1. Would be great if output can be specified in .exr or other format instead of .hdr ; is it possible?
2. Curious - how can I learn more about the details of this ".hdr" format e.g. precision per pixel? does it store linear fp16? whats relationship of pixel value and nits? etc. Also, would be great if you can suggest any free image viewer to view .hdr file? 
3. If only ".hdr" supported, can you recommended a tool to convert say to .exr or other format(e.g. tiff)? Or even better - eventually, trying to understand a way to convert sequence of .hdr (or other format) in say HEVC Main 10 video (.mp4) sequence to be able to view it on HDR monitor. Any suggestions?

**Comment by dmarnerides** [comment]
Hi
1. Yes, I just added a flag --use_exr which will save the predicted images in .exr format
2. The .hdr format is essentially the RGBE radiance format by Greg Ward. It saves each colour as 8 bit, with an extra 8bit exponent (E channel). More information [here](https://www.sciencedirect.com/science/article/pii/B9780080507545500256) (paywall), [here](https://www.graphics.cornell.edu/~bjw/rgbe.html) and [here](https://www.pauldebevec.com/IBL2003/GWcourseTalk-IBL2003.pdf). To view the files you can use [HDRShop](http://www.hdrshop.com/) or [Tev](https://github.com/Tom94/tev) which also supports EXR, or the online [OpenHDR](https://viewer.openhdr.org/) viewer.
3. Doing video is a bit more involved and I'm not sure which would be the right format / codec etc to do this. If you have any experience with it please share and feel free to do a pull request.

**Comment by ittim4** [comment]
Thanks a lot dmarnerides for adding the flag! Thanks for the details on points 2 and 3 as well. This is so helpful! 
(P.S: Sorry to respond late, was away for last week)
