### ISSUE TITLE
iterating over png/jpg dataset from a folder

### ISSUE THREAD

**Issue by ittim4** [dmarnerides/hdr-expandnet#7]
Is there a way to specify absolute or relative path for input folder so that all images in input folder will be processed? If not, can it be added? There is already --out option for specifying out dir, but no similar option for specifying input directory.
E.g.  Tried "python expand.py in_dir --out results" or "python expand.py in_dir\*.png --out results" ; it doesn't work as we get error message saying "Could not load in_dir" or "Could not load in_dir\*.png", though folder in_dir exists at correct location.

**Comment by dmarnerides** [comment]
Hi, can you try this and let me know if it works?
```bash
python expand.py in_dir/*.png --out results
```

**Comment by ittim4** [comment]
Tried; it doesn't work.

**Comment by ittim4** [comment]
Currently have a workaround for this to call for each image separately; but just checking in if there was any update here.

**Comment by dmarnerides** [comment]
Update: The new commit works with LDR directories
```bash
python expand.py path/to/ldr_dir
```
